export interface Bank {
  id: string;
  name: string;
  type: "bank" | "credit_union" | "fintech" | "neobank";
  bonusAmount: number;
  directDepositRequired: number;
  bonusPercentage: number;
  ewsReporting: boolean;
  noMonthlyMinimum: boolean;
  requiresBiometrics: boolean;
  timeToBonus: number;
  minDirectDeposits: number;
  directDepositPeriodDays: number;
  accountFee: number;
  category: string[];
  logoColor: string;
  logoAccent: string;
  state: string;
  signupUrl: string;
  signupQuestions: SignupQuestion[];
  notes: string;
  rating: number;
}

export interface SignupQuestion {
  field: string;
  label: string;
  type: "text" | "email" | "phone" | "ssn" | "date" | "address" | "select";
  required: boolean;
}

const commonSignupQuestions: SignupQuestion[] = [
  { field: "firstName", label: "First Name", type: "text", required: true },
  { field: "lastName", label: "Last Name", type: "text", required: true },
  { field: "email", label: "Email Address", type: "email", required: true },
  { field: "phone", label: "Phone Number", type: "phone", required: true },
  { field: "ssn", label: "Social Security Number", type: "ssn", required: true },
  { field: "dob", label: "Date of Birth", type: "date", required: true },
  { field: "address", label: "Street Address", type: "address", required: true },
  { field: "city", label: "City", type: "text", required: true },
  { field: "state", label: "State", type: "select", required: true },
  { field: "zip", label: "ZIP Code", type: "text", required: true },
];

export const BANKS: Bank[] = [
  {
    id: "chase-total",
    name: "Chase Total Checking",
    type: "bank",
    bonusAmount: 300,
    directDepositRequired: 500,
    bonusPercentage: 60.0,
    ewsReporting: true,
    noMonthlyMinimum: false,
    requiresBiometrics: false,
    timeToBonus: 90,
    minDirectDeposits: 1,
    directDepositPeriodDays: 90,
    accountFee: 12,
    category: ["major-bank", "nationwide"],
    logoColor: "#117ACA",
    logoAccent: "#FFFFFF",
    state: "Nationwide",
    signupUrl: "https://chase.com",
    signupQuestions: commonSignupQuestions,
    notes: "Monthly fee waived with $500 direct deposit",
    rating: 4.2,
  },
  {
    id: "sofi-checking",
    name: "SoFi Checking & Savings",
    type: "fintech",
    bonusAmount: 300,
    directDepositRequired: 1000,
    bonusPercentage: 30.0,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 25,
    minDirectDeposits: 1,
    directDepositPeriodDays: 25,
    accountFee: 0,
    category: ["fintech", "no-ews", "no-fee"],
    logoColor: "#6C30E0",
    logoAccent: "#FFFFFF",
    state: "Nationwide",
    signupUrl: "https://sofi.com",
    signupQuestions: commonSignupQuestions,
    notes: "No EWS reporting. No monthly fees. Fastest bonus payout.",
    rating: 4.8,
  },
  {
    id: "citi-checking",
    name: "Citi Priority Checking",
    type: "bank",
    bonusAmount: 2000,
    directDepositRequired: 30000,
    bonusPercentage: 6.67,
    ewsReporting: true,
    noMonthlyMinimum: false,
    requiresBiometrics: false,
    timeToBonus: 90,
    minDirectDeposits: 2,
    directDepositPeriodDays: 60,
    accountFee: 30,
    category: ["major-bank", "high-bonus"],
    logoColor: "#003B70",
    logoAccent: "#E31837",
    state: "Nationwide",
    signupUrl: "https://citi.com",
    signupQuestions: commonSignupQuestions,
    notes: "High bonus but requires large direct deposit amount",
    rating: 3.9,
  },
  {
    id: "us-bank-checking",
    name: "U.S. Bank Smartly Checking",
    type: "bank",
    bonusAmount: 400,
    directDepositRequired: 3000,
    bonusPercentage: 13.33,
    ewsReporting: true,
    noMonthlyMinimum: false,
    requiresBiometrics: false,
    timeToBonus: 90,
    minDirectDeposits: 2,
    directDepositPeriodDays: 60,
    accountFee: 6.95,
    category: ["major-bank"],
    logoColor: "#004B87",
    logoAccent: "#CE1126",
    state: "Nationwide",
    signupUrl: "https://usbank.com",
    signupQuestions: commonSignupQuestions,
    notes: "Available in select states",
    rating: 3.8,
  },
  {
    id: "td-bank-beyond",
    name: "TD Bank Beyond Checking",
    type: "bank",
    bonusAmount: 300,
    directDepositRequired: 2500,
    bonusPercentage: 12.0,
    ewsReporting: true,
    noMonthlyMinimum: false,
    requiresBiometrics: false,
    timeToBonus: 95,
    minDirectDeposits: 1,
    directDepositPeriodDays: 60,
    accountFee: 25,
    category: ["major-bank", "east-coast"],
    logoColor: "#2B8C1E",
    logoAccent: "#FFFFFF",
    state: "East Coast",
    signupUrl: "https://td.com",
    signupQuestions: commonSignupQuestions,
    notes: "Available in eastern states",
    rating: 3.7,
  },
  {
    id: "current-checking",
    name: "Current Premium",
    type: "neobank",
    bonusAmount: 100,
    directDepositRequired: 200,
    bonusPercentage: 50.0,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 60,
    minDirectDeposits: 1,
    directDepositPeriodDays: 30,
    accountFee: 4.99,
    category: ["neobank", "no-ews"],
    logoColor: "#00B286",
    logoAccent: "#FFFFFF",
    state: "Nationwide",
    signupUrl: "https://current.com",
    signupQuestions: commonSignupQuestions,
    notes: "No EWS. Fast mobile-first experience.",
    rating: 4.5,
  },
  {
    id: "upgrade-checking",
    name: "Upgrade Rewards Checking",
    type: "fintech",
    bonusAmount: 200,
    directDepositRequired: 1000,
    bonusPercentage: 20.0,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 120,
    minDirectDeposits: 3,
    directDepositPeriodDays: 120,
    accountFee: 0,
    category: ["fintech", "no-ews", "no-fee"],
    logoColor: "#FF5000",
    logoAccent: "#FFFFFF",
    state: "Nationwide",
    signupUrl: "https://upgrade.com",
    signupQuestions: commonSignupQuestions,
    notes: "No EWS. Earns cash back on purchases.",
    rating: 4.3,
  },
  {
    id: "chime-checking",
    name: "Chime Checking",
    type: "neobank",
    bonusAmount: 100,
    directDepositRequired: 200,
    bonusPercentage: 50.0,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 60,
    minDirectDeposits: 2,
    directDepositPeriodDays: 60,
    accountFee: 0,
    category: ["neobank", "no-ews", "no-fee"],
    logoColor: "#1EC677",
    logoAccent: "#FFFFFF",
    state: "Nationwide",
    signupUrl: "https://chime.com",
    signupQuestions: commonSignupQuestions,
    notes: "No EWS. Very easy approval.",
    rating: 4.6,
  },
  {
    id: "axos-rewards",
    name: "Axos Rewards Checking",
    type: "bank",
    bonusAmount: 300,
    directDepositRequired: 1500,
    bonusPercentage: 20.0,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 75,
    minDirectDeposits: 2,
    directDepositPeriodDays: 60,
    accountFee: 0,
    category: ["online-bank", "no-ews", "no-fee"],
    logoColor: "#002D62",
    logoAccent: "#0095D3",
    state: "Nationwide",
    signupUrl: "https://axosbank.com",
    signupQuestions: commonSignupQuestions,
    notes: "No EWS reporting. High interest checking.",
    rating: 4.4,
  },
  {
    id: "bnb-high-yield",
    name: "Bread Financial Checking",
    type: "bank",
    bonusAmount: 250,
    directDepositRequired: 1000,
    bonusPercentage: 25.0,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 60,
    minDirectDeposits: 1,
    directDepositPeriodDays: 60,
    accountFee: 0,
    category: ["online-bank", "no-ews"],
    logoColor: "#FF6B00",
    logoAccent: "#FFFFFF",
    state: "Nationwide",
    signupUrl: "https://breadfinancial.com",
    signupQuestions: commonSignupQuestions,
    notes: "No EWS. Competitive APY on balances.",
    rating: 4.2,
  },
  {
    id: "varo-checking",
    name: "Varo Bank Checking",
    type: "neobank",
    bonusAmount: 75,
    directDepositRequired: 200,
    bonusPercentage: 37.5,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 30,
    minDirectDeposits: 1,
    directDepositPeriodDays: 30,
    accountFee: 0,
    category: ["neobank", "no-ews", "no-fee"],
    logoColor: "#6441A5",
    logoAccent: "#FFFFFF",
    state: "Nationwide",
    signupUrl: "https://varomoney.com",
    signupQuestions: commonSignupQuestions,
    notes: "No EWS. FDIC insured neobank.",
    rating: 4.1,
  },
  {
    id: "bluevine-business",
    name: "Bluevine Business Checking",
    type: "fintech",
    bonusAmount: 500,
    directDepositRequired: 5000,
    bonusPercentage: 10.0,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 90,
    minDirectDeposits: 2,
    directDepositPeriodDays: 60,
    accountFee: 0,
    category: ["fintech", "business", "no-ews"],
    logoColor: "#0079FF",
    logoAccent: "#FFFFFF",
    state: "Nationwide",
    signupUrl: "https://bluevine.com",
    signupQuestions: commonSignupQuestions,
    notes: "Business accounts only. No EWS.",
    rating: 4.5,
  },
  {
    id: "wf-everyday",
    name: "Wells Fargo Everyday Checking",
    type: "bank",
    bonusAmount: 325,
    directDepositRequired: 1000,
    bonusPercentage: 32.5,
    ewsReporting: true,
    noMonthlyMinimum: false,
    requiresBiometrics: false,
    timeToBonus: 90,
    minDirectDeposits: 1,
    directDepositPeriodDays: 90,
    accountFee: 10,
    category: ["major-bank", "nationwide"],
    logoColor: "#CC0000",
    logoAccent: "#FFCD00",
    state: "Nationwide",
    signupUrl: "https://wellsfargo.com",
    signupQuestions: commonSignupQuestions,
    notes: "Large branch network",
    rating: 3.5,
  },
  {
    id: "boa-advantage",
    name: "Bank of America Advantage",
    type: "bank",
    bonusAmount: 200,
    directDepositRequired: 2000,
    bonusPercentage: 10.0,
    ewsReporting: true,
    noMonthlyMinimum: false,
    requiresBiometrics: false,
    timeToBonus: 90,
    minDirectDeposits: 2,
    directDepositPeriodDays: 90,
    accountFee: 12,
    category: ["major-bank", "nationwide"],
    logoColor: "#E31837",
    logoAccent: "#012169",
    state: "Nationwide",
    signupUrl: "https://bankofamerica.com",
    signupQuestions: commonSignupQuestions,
    notes: "Preferred Rewards can eliminate fee",
    rating: 3.6,
  },
  {
    id: "one-finance",
    name: "ONE Finance",
    type: "fintech",
    bonusAmount: 150,
    directDepositRequired: 500,
    bonusPercentage: 30.0,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 60,
    minDirectDeposits: 2,
    directDepositPeriodDays: 60,
    accountFee: 0,
    category: ["fintech", "no-ews", "no-fee"],
    logoColor: "#0EA5E9",
    logoAccent: "#FFFFFF",
    state: "Nationwide",
    signupUrl: "https://one.app",
    signupQuestions: commonSignupQuestions,
    notes: "No EWS. Walmart-backed fintech.",
    rating: 4.0,
  },
  {
    id: "aspiration-spend",
    name: "Aspiration Spend & Save",
    type: "fintech",
    bonusAmount: 100,
    directDepositRequired: 500,
    bonusPercentage: 20.0,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 30,
    minDirectDeposits: 1,
    directDepositPeriodDays: 30,
    accountFee: 0,
    category: ["fintech", "no-ews", "eco"],
    logoColor: "#38B2AC",
    logoAccent: "#FFFFFF",
    state: "Nationwide",
    signupUrl: "https://aspiration.com",
    signupQuestions: commonSignupQuestions,
    notes: "No EWS. Climate-focused fintech.",
    rating: 3.9,
  },
  {
    id: "navy-federal",
    name: "Navy Federal Credit Union",
    type: "credit_union",
    bonusAmount: 250,
    directDepositRequired: 500,
    bonusPercentage: 50.0,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 90,
    minDirectDeposits: 2,
    directDepositPeriodDays: 90,
    accountFee: 0,
    category: ["credit-union", "no-ews", "military"],
    logoColor: "#003087",
    logoAccent: "#C8A951",
    state: "Nationwide",
    signupUrl: "https://navyfederal.org",
    signupQuestions: commonSignupQuestions,
    notes: "Military members and families only. No EWS.",
    rating: 4.9,
  },
  {
    id: "alliant-checking",
    name: "Alliant Credit Union Checking",
    type: "credit_union",
    bonusAmount: 200,
    directDepositRequired: 500,
    bonusPercentage: 40.0,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 90,
    minDirectDeposits: 1,
    directDepositPeriodDays: 90,
    accountFee: 0,
    category: ["credit-union", "no-ews", "online"],
    logoColor: "#005DAA",
    logoAccent: "#FFCD00",
    state: "Nationwide",
    signupUrl: "https://alliantcreditunion.org",
    signupQuestions: commonSignupQuestions,
    notes: "No EWS. Open to anyone via donation.",
    rating: 4.7,
  },
  {
    id: "penfed-checking",
    name: "PenFed Credit Union Checking",
    type: "credit_union",
    bonusAmount: 250,
    directDepositRequired: 500,
    bonusPercentage: 50.0,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 60,
    minDirectDeposits: 1,
    directDepositPeriodDays: 60,
    accountFee: 0,
    category: ["credit-union", "no-ews", "military"],
    logoColor: "#CF4520",
    logoAccent: "#FFFFFF",
    state: "Nationwide",
    signupUrl: "https://penfed.org",
    signupQuestions: commonSignupQuestions,
    notes: "No EWS. Open to anyone.",
    rating: 4.6,
  },
  {
    id: "discover-cashback",
    name: "Discover Cashback Checking",
    type: "bank",
    bonusAmount: 150,
    directDepositRequired: 500,
    bonusPercentage: 30.0,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 45,
    minDirectDeposits: 1,
    directDepositPeriodDays: 45,
    accountFee: 0,
    category: ["online-bank", "no-ews", "no-fee"],
    logoColor: "#F36C2E",
    logoAccent: "#FFFFFF",
    state: "Nationwide",
    signupUrl: "https://discover.com",
    signupQuestions: commonSignupQuestions,
    notes: "No EWS. 1% cashback on debit purchases.",
    rating: 4.5,
  },
  {
    id: "fifth-third-momentum",
    name: "Fifth Third Momentum Checking",
    type: "bank",
    bonusAmount: 275,
    directDepositRequired: 1000,
    bonusPercentage: 27.5,
    ewsReporting: true,
    noMonthlyMinimum: false,
    requiresBiometrics: false,
    timeToBonus: 75,
    minDirectDeposits: 2,
    directDepositPeriodDays: 45,
    accountFee: 0,
    category: ["major-bank", "midwest"],
    logoColor: "#18A34A",
    logoAccent: "#FFFFFF",
    state: "Midwest/Southeast",
    signupUrl: "https://53.com",
    signupQuestions: commonSignupQuestions,
    notes: "Free with no minimum balance",
    rating: 4.0,
  },
  {
    id: "huntington-accelerated",
    name: "Huntington Accelerated Savings",
    type: "bank",
    bonusAmount: 400,
    directDepositRequired: 1000,
    bonusPercentage: 40.0,
    ewsReporting: true,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 90,
    minDirectDeposits: 3,
    directDepositPeriodDays: 90,
    accountFee: 0,
    category: ["major-bank", "midwest"],
    logoColor: "#007A3D",
    logoAccent: "#FFFFFF",
    state: "Midwest",
    signupUrl: "https://huntington.com",
    signupQuestions: commonSignupQuestions,
    notes: "No monthly minimum balance requirement",
    rating: 4.1,
  },
  {
    id: "keybank-key-smart",
    name: "KeyBank Key Smart Checking",
    type: "bank",
    bonusAmount: 200,
    directDepositRequired: 500,
    bonusPercentage: 40.0,
    ewsReporting: true,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 60,
    minDirectDeposits: 1,
    directDepositPeriodDays: 60,
    accountFee: 0,
    category: ["major-bank", "northeast"],
    logoColor: "#EE0000",
    logoAccent: "#FFFFFF",
    state: "Select States",
    signupUrl: "https://key.com",
    signupQuestions: commonSignupQuestions,
    notes: "No minimum balance requirement",
    rating: 3.8,
  },
  {
    id: "oxygen-checking",
    name: "Oxygen Business Banking",
    type: "neobank",
    bonusAmount: 100,
    directDepositRequired: 500,
    bonusPercentage: 20.0,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 30,
    minDirectDeposits: 1,
    directDepositPeriodDays: 30,
    accountFee: 0,
    category: ["neobank", "business", "no-ews"],
    logoColor: "#7B2FBE",
    logoAccent: "#FFFFFF",
    state: "Nationwide",
    signupUrl: "https://oxygen.us",
    signupQuestions: commonSignupQuestions,
    notes: "No EWS. Great for freelancers.",
    rating: 4.2,
  },
  {
    id: "lili-checking",
    name: "Lili Business Checking",
    type: "neobank",
    bonusAmount: 100,
    directDepositRequired: 250,
    bonusPercentage: 40.0,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 30,
    minDirectDeposits: 1,
    directDepositPeriodDays: 30,
    accountFee: 0,
    category: ["neobank", "business", "no-ews"],
    logoColor: "#FF7043",
    logoAccent: "#FFFFFF",
    state: "Nationwide",
    signupUrl: "https://lili.co",
    signupQuestions: commonSignupQuestions,
    notes: "No EWS. Designed for freelancers and self-employed.",
    rating: 4.3,
  },
  {
    id: "mercury-checking",
    name: "Mercury Business Checking",
    type: "fintech",
    bonusAmount: 500,
    directDepositRequired: 10000,
    bonusPercentage: 5.0,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 90,
    minDirectDeposits: 2,
    directDepositPeriodDays: 60,
    accountFee: 0,
    category: ["fintech", "business", "no-ews"],
    logoColor: "#5C4EE5",
    logoAccent: "#FFFFFF",
    state: "Nationwide",
    signupUrl: "https://mercury.com",
    signupQuestions: commonSignupQuestions,
    notes: "No EWS. Popular with startups and tech companies.",
    rating: 4.7,
  },
  {
    id: "nbkc-checking",
    name: "nbkc Bank Checking",
    type: "bank",
    bonusAmount: 500,
    directDepositRequired: 2000,
    bonusPercentage: 25.0,
    ewsReporting: false,
    noMonthlyMinimum: true,
    requiresBiometrics: false,
    timeToBonus: 60,
    minDirectDeposits: 2,
    directDepositPeriodDays: 60,
    accountFee: 0,
    category: ["online-bank", "no-ews", "no-fee"],
    logoColor: "#003EA1",
    logoAccent: "#FFFFFF",
    state: "Nationwide",
    signupUrl: "https://nbkc.com",
    signupQuestions: commonSignupQuestions,
    notes: "No EWS. No ATM fees nationwide.",
    rating: 4.5,
  },
];

export const getEWSFreebanks = () => BANKS.filter(b => !b.ewsReporting);
export const getNoMinimumBanks = () => BANKS.filter(b => b.noMonthlyMinimum);
export const getNoBiometricBanks = () => BANKS.filter(b => !b.requiresBiometrics);
export const sortByBonusAmount = (banks: Bank[]) => [...banks].sort((a, b) => b.bonusAmount - a.bonusAmount);
export const sortByBonusPercentage = (banks: Bank[]) => [...banks].sort((a, b) => b.bonusPercentage - a.bonusPercentage);
export const sortByRating = (banks: Bank[]) => [...banks].sort((a, b) => b.rating - a.rating);
export const sortByTimeToBonus = (banks: Bank[]) => [...banks].sort((a, b) => a.timeToBonus - b.timeToBonus);

export const CHROME_EXTENSION_TEMPLATE = {
  manifest_version: 3,
  name: "BigBankBonus AutoFill",
  version: "1.0.0",
  description: "Auto-fill bank account signup forms with your information",
  permissions: ["activeTab", "storage"],
  action: { default_popup: "popup.html", default_icon: { "16": "icon16.png" } },
  content_scripts: [{
    matches: ["<all_urls>"],
    js: ["content.js"],
  }],
  autofill_fields: {
    firstName: { selectors: ["input[name='firstName']", "input[id='firstName']", "input[placeholder*='First']"] },
    lastName: { selectors: ["input[name='lastName']", "input[id='lastName']", "input[placeholder*='Last']"] },
    email: { selectors: ["input[type='email']", "input[name='email']", "input[id='email']"] },
    phone: { selectors: ["input[type='tel']", "input[name='phone']", "input[name='phoneNumber']"] },
    ssn: { selectors: ["input[name='ssn']", "input[name='socialSecurity']", "input[id='ssn']"] },
    dob: { selectors: ["input[name='dateOfBirth']", "input[name='dob']", "input[id='dateOfBirth']"] },
    address: { selectors: ["input[name='address']", "input[name='streetAddress']", "input[id='address1']"] },
    city: { selectors: ["input[name='city']", "input[id='city']"] },
    state: { selectors: ["select[name='state']", "select[id='state']"] },
    zip: { selectors: ["input[name='zip']", "input[name='zipCode']", "input[name='postalCode']"] },
  },
};
