import { Router, type IRouter } from "express";
import healthRouter from "./health";
import agentRouter from "./agent";
import bonusesRouter from "./bonuses";
import plaidRouter from "./plaid";
import autopayRouter from "./autopay";
import subscriptionsRouter from "./subscriptions";
import authRouter from "./auth";
import monitorRouter from "./monitor";
import storageRouter from "./storage";
import uploadsRouter from "./uploads";
import recommendationsRouter from "./recommendations";
import depositRouter from "./deposit";
import webhooksRouter from "./webhooks";
import statementRouter from "./statement";
import salesRouter from "./sales";
import ownerRouter from "./owner";
import waitlistRouter from "./waitlist";

const router: IRouter = Router();

router.use(healthRouter);
router.use(agentRouter);
router.use(bonusesRouter);
router.use(plaidRouter);
router.use(autopayRouter);
router.use(subscriptionsRouter);
router.use(authRouter);
router.use(waitlistRouter);
router.use(monitorRouter);
router.use(storageRouter);
router.use(uploadsRouter);
router.use(recommendationsRouter);
router.use(depositRouter);
router.use(webhooksRouter);
router.use(statementRouter);
router.use(salesRouter);
router.use(ownerRouter);

export default router;
