export interface MonitorSource {
  url: string;
  name: string;
  category: "cfpb" | "reddit" | "doc" | "bank_newsroom" | "aggregator" | "forum" | "news" | "federal" | "state" | "consumer";
  parserType: "rss" | "html" | "json" | "api";
  pollingFrequencyHours: number;
  keywords?: string[];
}

const CFPB_SOURCES: MonitorSource[] = [
  { url: "https://www.consumerfinance.gov/data-research/consumer-complaints/search/api/v1/?format=json&product=Checking+or+savings+account&size=50", name: "CFPB Checking Complaints", category: "cfpb", parserType: "json", pollingFrequencyHours: 6, keywords: ["ChexSystems", "EWS", "Early Warning", "denial", "closed account"] },
  { url: "https://www.consumerfinance.gov/data-research/consumer-complaints/search/api/v1/?format=json&product=Bank+account+or+service&size=50", name: "CFPB Bank Service Complaints", category: "cfpb", parserType: "json", pollingFrequencyHours: 6, keywords: ["ChexSystems", "EWS", "Early Warning"] },
  { url: "https://www.consumerfinance.gov/rules-policy/final-rules/", name: "CFPB Final Rules", category: "cfpb", parserType: "html", pollingFrequencyHours: 24, keywords: ["bank account", "checking", "deposit", "consumer reporting"] },
  { url: "https://www.consumerfinance.gov/rules-policy/proposed-rules/", name: "CFPB Proposed Rules", category: "cfpb", parserType: "html", pollingFrequencyHours: 24 },
  { url: "https://www.consumerfinance.gov/about-us/newsroom/", name: "CFPB Newsroom", category: "cfpb", parserType: "html", pollingFrequencyHours: 12 },
  { url: "https://www.consumerfinance.gov/data-research/consumer-complaints/search/api/v1/?format=json&company=Early+Warning+Services&size=100", name: "CFPB EWS Complaints", category: "cfpb", parserType: "json", pollingFrequencyHours: 6, keywords: ["EWS", "Zelle", "denial", "freeze"] },
  { url: "https://www.consumerfinance.gov/data-research/consumer-complaints/search/api/v1/?format=json&company=Chex+Systems&size=100", name: "CFPB ChexSystems Complaints", category: "cfpb", parserType: "json", pollingFrequencyHours: 6, keywords: ["ChexSystems", "record", "dispute"] },
  { url: "https://www.consumerfinance.gov/data-research/consumer-complaints/search/api/v1/?format=json&company=Early+Warning+Services%2C+LLC&size=100", name: "CFPB EWS LLC Complaints", category: "cfpb", parserType: "json", pollingFrequencyHours: 6 },
  { url: "https://api.consumerfinance.gov/data/complaints.json?field=product&value=Checking+or+savings+account&size=25", name: "CFPB Complaints API v2", category: "cfpb", parserType: "json", pollingFrequencyHours: 6 },
  { url: "https://www.consumerfinance.gov/enforcement/actions/", name: "CFPB Enforcement Actions", category: "cfpb", parserType: "html", pollingFrequencyHours: 24 },
];

const REDDIT_SOURCES: MonitorSource[] = [
  { url: "https://www.reddit.com/r/churning/new.json?limit=100", name: "Reddit r/churning New", category: "reddit", parserType: "json", pollingFrequencyHours: 1, keywords: ["ChexSystems", "EWS", "Early Warning", "bank bonus", "denied", "opened"] },
  { url: "https://www.reddit.com/r/personalfinance/new.json?limit=100", name: "Reddit r/personalfinance New", category: "reddit", parserType: "json", pollingFrequencyHours: 2, keywords: ["ChexSystems", "EWS", "bank account", "denied"] },
  { url: "https://www.reddit.com/r/churning/search.json?q=ChexSystems&sort=new&limit=50", name: "Reddit ChexSystems Search", category: "reddit", parserType: "json", pollingFrequencyHours: 3 },
  { url: "https://www.reddit.com/r/churning/search.json?q=EWS+bank+bonus&sort=new&limit=50", name: "Reddit EWS Search", category: "reddit", parserType: "json", pollingFrequencyHours: 3 },
  { url: "https://www.reddit.com/r/personalfinance/search.json?q=ChexSystems+denied&sort=new&limit=50", name: "Reddit PF ChexSystems Denied", category: "reddit", parserType: "json", pollingFrequencyHours: 4 },
  { url: "https://www.reddit.com/r/banking/new.json?limit=100", name: "Reddit r/banking New", category: "reddit", parserType: "json", pollingFrequencyHours: 2, keywords: ["ChexSystems", "EWS", "bonus", "policy"] },
  { url: "https://www.reddit.com/r/banking/search.json?q=bank+bonus+ChexSystems&sort=new&limit=50", name: "Reddit Banking ChexSystems", category: "reddit", parserType: "json", pollingFrequencyHours: 4 },
  { url: "https://www.reddit.com/r/frugal/search.json?q=bank+bonus&sort=new&limit=50", name: "Reddit Frugal Bank Bonus", category: "reddit", parserType: "json", pollingFrequencyHours: 6 },
  { url: "https://www.reddit.com/r/financialindependence/search.json?q=bank+bonus&sort=new&limit=50", name: "Reddit FI Bank Bonus", category: "reddit", parserType: "json", pollingFrequencyHours: 6 },
  { url: "https://www.reddit.com/r/CreditCards/search.json?q=bank+bonus+EWS&sort=new&limit=50", name: "Reddit CreditCards EWS", category: "reddit", parserType: "json", pollingFrequencyHours: 4 },
  { url: "https://www.reddit.com/r/churning/comments/search.json?q=early+warning+services&sort=new&limit=50", name: "Reddit Churning EWS Comments", category: "reddit", parserType: "json", pollingFrequencyHours: 3 },
  { url: "https://www.reddit.com/r/povertyfinance/search.json?q=ChexSystems+bank&sort=new&limit=50", name: "Reddit PovertyFinance ChexSystems", category: "reddit", parserType: "json", pollingFrequencyHours: 6 },
  { url: "https://www.reddit.com/r/personalfinance/search.json?q=bank+bonus+checking&sort=new&limit=50", name: "Reddit PF Bank Bonuses", category: "reddit", parserType: "json", pollingFrequencyHours: 4 },
  { url: "https://www.reddit.com/r/deals/search.json?q=bank+bonus&sort=new&limit=50", name: "Reddit Deals Bank Bonus", category: "reddit", parserType: "json", pollingFrequencyHours: 4 },
  { url: "https://www.reddit.com/r/beermoney/search.json?q=bank+bonus&sort=new&limit=50", name: "Reddit Beermoney Bank Bonus", category: "reddit", parserType: "json", pollingFrequencyHours: 6 },
  { url: "https://www.reddit.com/r/mildlyinfuriating/search.json?q=ChexSystems&sort=new&limit=25", name: "Reddit ChexSystems Frustration", category: "reddit", parserType: "json", pollingFrequencyHours: 12 },
  { url: "https://www.reddit.com/r/churning/wiki/index.json", name: "Reddit Churning Wiki", category: "reddit", parserType: "json", pollingFrequencyHours: 24 },
  { url: "https://www.reddit.com/r/churning/search.json?q=bank+account+bonus+data+points&sort=new&limit=100", name: "Reddit Churning DPs", category: "reddit", parserType: "json", pollingFrequencyHours: 2 },
  { url: "https://www.reddit.com/r/personalfinance/search.json?q=early+warning+services&sort=new&limit=50", name: "Reddit PF EWS", category: "reddit", parserType: "json", pollingFrequencyHours: 6 },
  { url: "https://www.reddit.com/r/investing/search.json?q=bank+bonus+interest&sort=new&limit=50", name: "Reddit Investing Bank Bonus", category: "reddit", parserType: "json", pollingFrequencyHours: 6 },
];

const DOC_SOURCES: MonitorSource[] = [
  { url: "https://www.doctorofcredit.com/feed/", name: "DoC RSS Feed", category: "doc", parserType: "rss", pollingFrequencyHours: 1, keywords: ["ChexSystems", "EWS", "bank bonus", "checking", "savings", "opened", "closed"] },
  { url: "https://www.doctorofcredit.com/category/bank-accounts/feed/", name: "DoC Bank Accounts Feed", category: "doc", parserType: "rss", pollingFrequencyHours: 1 },
  { url: "https://www.doctorofcredit.com/category/bank-deals/feed/", name: "DoC Bank Deals Feed", category: "doc", parserType: "rss", pollingFrequencyHours: 1 },
  { url: "https://www.doctorofcredit.com/tag/chexsystems/feed/", name: "DoC ChexSystems Tag", category: "doc", parserType: "rss", pollingFrequencyHours: 3 },
  { url: "https://www.doctorofcredit.com/tag/early-warning-services/feed/", name: "DoC EWS Tag", category: "doc", parserType: "rss", pollingFrequencyHours: 3 },
  { url: "https://www.doctorofcredit.com/tag/bank-account-bonus/feed/", name: "DoC Bank Account Bonus Tag", category: "doc", parserType: "rss", pollingFrequencyHours: 2 },
  { url: "https://www.doctorofcredit.com/tag/checking-account-bonus/feed/", name: "DoC Checking Account Bonus Tag", category: "doc", parserType: "rss", pollingFrequencyHours: 2 },
  { url: "https://www.doctorofcredit.com/tag/savings-account-bonus/feed/", name: "DoC Savings Account Bonus Tag", category: "doc", parserType: "rss", pollingFrequencyHours: 2 },
  { url: "https://www.doctorofcredit.com/category/news/feed/", name: "DoC News Feed", category: "doc", parserType: "rss", pollingFrequencyHours: 2 },
  { url: "https://www.doctorofcredit.com/tag/no-chexsystems/feed/", name: "DoC No ChexSystems Tag", category: "doc", parserType: "rss", pollingFrequencyHours: 3 },
  { url: "https://www.doctorofcredit.com/tag/second-chance-checking/feed/", name: "DoC Second Chance Checking", category: "doc", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.doctorofcredit.com/tag/direct-deposit/feed/", name: "DoC Direct Deposit Tag", category: "doc", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://www.doctorofcredit.com/tag/soft-pull/feed/", name: "DoC Soft Pull Tag", category: "doc", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://www.doctorofcredit.com/tag/hard-pull/feed/", name: "DoC Hard Pull Tag", category: "doc", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.doctorofcredit.com/best-bank-account-bonuses/feed/", name: "DoC Best Bank Bonuses", category: "doc", parserType: "rss", pollingFrequencyHours: 2 },
  { url: "https://www.doctorofcredit.com/tag/nationwide/feed/", name: "DoC Nationwide Deals", category: "doc", parserType: "rss", pollingFrequencyHours: 2 },
  { url: "https://www.doctorofcredit.com/tag/business-checking/feed/", name: "DoC Business Checking", category: "doc", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://www.doctorofcredit.com/tag/expired/feed/", name: "DoC Expired Deals", category: "doc", parserType: "rss", pollingFrequencyHours: 3 },
  { url: "https://www.doctorofcredit.com/tag/bank-of-america/feed/", name: "DoC Bank of America", category: "doc", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.doctorofcredit.com/tag/chase/feed/", name: "DoC Chase", category: "doc", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://www.doctorofcredit.com/tag/wells-fargo/feed/", name: "DoC Wells Fargo", category: "doc", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.doctorofcredit.com/tag/citibank/feed/", name: "DoC Citi", category: "doc", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.doctorofcredit.com/tag/us-bank/feed/", name: "DoC US Bank", category: "doc", parserType: "rss", pollingFrequencyHours: 6 },
];

const BANK_NEWSROOM_SOURCES: MonitorSource[] = [
  { url: "https://newsroom.bankofamerica.com/feed", name: "Bank of America Newsroom", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12, keywords: ["ChexSystems", "EWS", "policy", "account", "checking"] },
  { url: "https://media.chase.com/news/rss.rss", name: "Chase Newsroom RSS", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://newsroom.td.com/us/en/news-releases/feed", name: "TD Bank Newsroom", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://newsroom.pnc.com/feed/", name: "PNC Newsroom", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://news.regions.com/feed/", name: "Regions Bank News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://newsroom.usbank.com/feed/", name: "US Bank Newsroom", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://ir.fith.com/rss/news-releases.xml", name: "Fifth Third Newsroom", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.huntington.com/Content/feeds/news-releases.rss", name: "Huntington News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://investor.ally.com/news-releases/rss/news-releases.xml", name: "Ally Financial News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://investor.sofi.com/news-releases/rss/news-releases.xml", name: "SoFi News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://news.pnc.com/feed/", name: "PNC News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.citigroup.com/citi/news/rss/index.rss", name: "Citigroup News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.wellsfargo.com/about/press/newsroom/rss.xml", name: "Wells Fargo Press", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://newsroom.bankofamerica.com/press-releases.rss", name: "BofA Press Releases", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://ir.discoverfinancial.com/news-releases/rss/news-releases.xml", name: "Discover Financial News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://investors.synchronyfinancial.com/news-releases/rss/news-releases.xml", name: "Synchrony News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://investors.capitalone.com/news-releases/rss/news-releases.xml", name: "Capital One News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://ir.barclaysus.com/news-releases/rss/news-releases.xml", name: "Barclays US News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.bmo.com/en-us/main/about-us/newsroom/feed/", name: "BMO Harris News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.key.com/news-releases/rss/news-releases.xml", name: "KeyBank News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.comerica.com/news-releases/rss/news-releases.xml", name: "Comerica News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.svb.com/news-releases/rss/news-releases.xml", name: "SVB News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.chime.com/news-releases/rss/news-releases.xml", name: "Chime News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://ir.current.com/news-releases/rss/news-releases.xml", name: "Current News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://newsroom.americanexpress.com/feed/", name: "AmEx Newsroom", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://investor.usaa.com/news-releases/rss/news-releases.xml", name: "USAA News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.navyfederal.org/news-releases/rss/news-releases.xml", name: "Navy Federal News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.citizens.com/news-releases/rss/news-releases.xml", name: "Citizens Bank News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.mmb.com/news-releases/rss/news-releases.xml", name: "M&T Bank News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.suntrust.com/news-releases/rss/news-releases.xml", name: "Truist News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.schwab.com/news-releases/rss/news-releases.xml", name: "Charles Schwab News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://ir.fidelity.com/news-releases/rss/news-releases.xml", name: "Fidelity News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.vanguard.com/news-releases/rss/news-releases.xml", name: "Vanguard News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://newsroom.wintrust.com/feed/", name: "Wintrust News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.fnb.com/news-releases/rss/news-releases.xml", name: "First National Bank News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.firsthorizon.com/news-releases/rss/news-releases.xml", name: "First Horizon News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.westernalliance.com/news-releases/rss/news-releases.xml", name: "Western Alliance News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.bankunited.com/news-releases/rss/news-releases.xml", name: "BankUnited News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://newsroom.hsbc.com/feed", name: "HSBC USA News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.associatedbanc-corp.com/news-releases/rss/news-releases.xml", name: "Associated Bank News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.glacier.com/news-releases/rss/news-releases.xml", name: "Glacier Bancorp News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.independent.bank.com/news-releases/rss/news-releases.xml", name: "Independent Bank News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.renasant.com/news-releases/rss/news-releases.xml", name: "Renasant News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.bankunited.com/news-releases/rss/news-releases.xml", name: "BankUnited IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.pacific-continental.com/news-releases/rss/news-releases.xml", name: "Pacific Continental News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.tristatecapital.com/news-releases/rss/news-releases.xml", name: "TriState Capital News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.seacoastbanking.com/news-releases/rss/news-releases.xml", name: "Seacoast Banking News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.lakeland.bank/news-releases/rss/news-releases.xml", name: "Lakeland Bancorp News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.homestreet.com/news-releases/rss/news-releases.xml", name: "HomeStreet News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
];

const AGGREGATOR_SOURCES: MonitorSource[] = [
  { url: "https://www.nerdwallet.com/blog/banking/feed/", name: "NerdWallet Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6, keywords: ["ChexSystems", "EWS", "bank bonus", "checking account"] },
  { url: "https://www.bankrate.com/banking/feed/", name: "Bankrate Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.mybanktracker.com/news/feed/", name: "MyBankTracker News", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://thepointsguy.com/news/feed/", name: "The Points Guy News", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://www.creditkarma.com/blog/feed/", name: "Credit Karma Blog", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://wallethub.com/edu/feed/", name: "WalletHub Edu", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.investopedia.com/banking-4427799/feed/", name: "Investopedia Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 8 },
  { url: "https://money.usnews.com/banking/rss", name: "US News Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 8 },
  { url: "https://www.valuepenguin.com/banking/rss.xml", name: "ValuePenguin Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.magnifymoney.com/blog/banking/feed/", name: "MagnifyMoney Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.moneyunder30.com/category/banking/feed/", name: "Money Under 30 Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.thebalancemoney.com/banking-4427799/feed/", name: "The Balance Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.bankingdive.com/feeds/news/", name: "Banking Dive News", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://www.americanbanker.com/feed", name: "American Banker Feed", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://www.housingwire.com/news/feed/", name: "HousingWire News", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.pymnts.com/tag/early-warning-services/feed/", name: "PYMNTS EWS", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.pymnts.com/tag/chexsystems/feed/", name: "PYMNTS ChexSystems", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://finextra.com/rss/headlines.aspx", name: "Finextra Headlines", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://finovate.com/feed/", name: "Finovate Feed", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.bankingtech.com/feed/", name: "Banking Tech Feed", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://thecollegeinvestor.com/category/banking/feed/", name: "College Investor Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.fool.com/the-ascent/banks/feed/", name: "Motley Fool Banks", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.gobankingrates.com/banking/feed/", name: "GOBankingRates Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://clark.com/personal-finance/banking/feed/", name: "Clark Howard Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.lendingtree.com/deposit-accounts/articles/rss.xml", name: "LendingTree Deposit Articles", category: "aggregator", parserType: "rss", pollingFrequencyHours: 8 },
  { url: "https://money.cnn.com/rss/money_pf_banking.rss", name: "CNN Money Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://www.wsj.com/xml/rss/3_7041.xml", name: "WSJ Banking RSS", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://feeds.reuters.com/reuters/businessNews", name: "Reuters Business News", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://www.ft.com/banking?format=rss", name: "FT Banking RSS", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.bloomberg.com/feeds/bview/news/industries/financial-services.rss", name: "Bloomberg Financial Services", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://www.consumerreports.org/cro/money/banking/index.htm/feed/", name: "Consumer Reports Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.smartasset.com/feed/", name: "SmartAsset Feed", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://dealmatch.com/blog/feed/", name: "DealMatch Blog", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.finder.com/us/blog/feed", name: "Finder Blog", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.supermoney.com/blog/feed/", name: "SuperMoney Blog", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.depositaccounts.com/blog/feed/", name: "Deposit Accounts Blog", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
];

const FORUM_SOURCES: MonitorSource[] = [
  { url: "https://ficoforums.myfico.com/t5/Banking/bd-p/Banking/rss", name: "myFICO Banking Forum", category: "forum", parserType: "rss", pollingFrequencyHours: 6, keywords: ["ChexSystems", "EWS", "denied", "opened", "bonus"] },
  { url: "https://www.flyertalk.com/forum/bank-account-bonuses-79/index.rss", name: "FlyerTalk Bank Bonuses", category: "forum", parserType: "rss", pollingFrequencyHours: 2 },
  { url: "https://forums.creditkarma.com/tags/chexsystems/feed", name: "Credit Karma Forums ChexSystems", category: "forum", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://community.bogleheads.org/forum/viewforum.php?f=2&feed=rss", name: "Bogleheads Personal Finance Forum", category: "forum", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.fatwallet.com/forums/finance/rss", name: "FatWallet Finance Forum", category: "forum", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://millionmilesecrets.com/feed/", name: "Million Mile Secrets", category: "forum", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://frequentmiler.com/feed/", name: "Frequent Miler", category: "forum", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://onemileatatime.com/feed/", name: "One Mile at a Time", category: "forum", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://viewfromthewing.com/feed/", name: "View From The Wing", category: "forum", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://www.creditcardspot.com/blog/feed/", name: "Credit Card Spot", category: "forum", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://moneysavingpro.com/feed/", name: "MoneySavingPro", category: "forum", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.bankdeals.net/feed/", name: "BankDeals.net", category: "forum", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://bankdealsguide.com/feed/", name: "Bank Deals Guide", category: "forum", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.checkingfinder.com/blog/feed/", name: "Checking Finder Blog", category: "forum", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://blog.icanbuild.it/feed/", name: "iCan Build It Blog", category: "forum", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://savingadvice.com/feed/", name: "Saving Advice Feed", category: "forum", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.frugalhacker.com/feed/", name: "Frugal Hacker Feed", category: "forum", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://feeds.feedburner.com/BankDeals", name: "Bank Deals FeedBurner", category: "forum", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.bankbonus.com/feed/", name: "BankBonus.com Feed", category: "forum", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://bankcheckingsavings.com/feed/", name: "Bank Checking Savings", category: "forum", parserType: "rss", pollingFrequencyHours: 6 },
];

const FEDERAL_SOURCES: MonitorSource[] = [
  { url: "https://www.federalreserve.gov/feeds/press_all.xml", name: "Federal Reserve Press", category: "federal", parserType: "rss", pollingFrequencyHours: 6, keywords: ["bank", "deposit", "consumer", "regulation"] },
  { url: "https://www.fdic.gov/news/press-releases/rss/", name: "FDIC Press Releases", category: "federal", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.occ.gov/news-issuances/news-releases/rss/rss.xml", name: "OCC News", category: "federal", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.ncua.gov/newsroom/rss-feed", name: "NCUA Newsroom", category: "federal", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.ftc.gov/news-events/rss.xml", name: "FTC News", category: "federal", parserType: "rss", pollingFrequencyHours: 12, keywords: ["banking", "consumer reporting", "financial"] },
  { url: "https://www.federalreserve.gov/feeds/h15.xml", name: "Federal Reserve H.15 Rates", category: "federal", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.federalreserve.gov/feeds/h41.xml", name: "Federal Reserve H.4.1", category: "federal", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.consumerfinance.gov/rules-policy/supervisory-guidance/rss/", name: "CFPB Supervisory Guidance", category: "federal", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.consumerfinance.gov/policy-compliance/guidance/advisory-opinions/rss/", name: "CFPB Advisory Opinions", category: "federal", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.federalregister.gov/api/v1/articles.json?conditions%5Bagencies%5D%5B%5D=consumer-financial-protection-bureau&per_page=20", name: "Federal Register CFPB Rules", category: "federal", parserType: "json", pollingFrequencyHours: 12 },
  { url: "https://www.federalregister.gov/api/v1/articles.json?conditions%5Bagencies%5D%5B%5D=federal-reserve-system&per_page=20", name: "Federal Register Fed Reserve", category: "federal", parserType: "json", pollingFrequencyHours: 12 },
  { url: "https://www.federalregister.gov/api/v1/articles.json?conditions%5Bagencies%5D%5B%5D=federal-deposit-insurance-corporation&per_page=20", name: "Federal Register FDIC", category: "federal", parserType: "json", pollingFrequencyHours: 12 },
  { url: "https://www.fdic.gov/regulations/applications/rss/", name: "FDIC Applications", category: "federal", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://occ.gov/news-issuances/bulletins/rss/", name: "OCC Bulletins", category: "federal", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.ffiec.gov/npw/FinancialReport/ReturnFinancialReport?rpt=BHC&selectedyear=2024", name: "FFIEC Bank Reports", category: "federal", parserType: "html", pollingFrequencyHours: 48 },
  { url: "https://www.federalreserve.gov/releases/h6/current/default.htm", name: "Fed Reserve Money Supply", category: "federal", parserType: "html", pollingFrequencyHours: 24 },
  { url: "https://www.consumerfinance.gov/data-research/research-reports/feed/", name: "CFPB Research Reports", category: "federal", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.fdic.gov/about/subscriptions/feeds/", name: "FDIC Subscription Feed", category: "federal", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.occ.gov/publications-and-resources/publications/quarterly-journal/rss/", name: "OCC Quarterly Journal", category: "federal", parserType: "rss", pollingFrequencyHours: 48 },
  { url: "https://www.ncua.gov/regulation-supervision/rss/regulatory-updates", name: "NCUA Regulatory Updates", category: "federal", parserType: "rss", pollingFrequencyHours: 24 },
];

const STATE_SOURCES: MonitorSource[] = [
  { url: "https://dfi.wa.gov/news/rss.xml", name: "WA DFI News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://dfpi.ca.gov/news/feed/", name: "CA DFPI News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.dfs.ny.gov/industry_guidance/press_releases/rss", name: "NY DFS Press Releases", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.state.tx.us/news/feed/", name: "TX Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.ofr.state.fl.us/banking-finance/newsroom/feed/", name: "FL Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.idfpr.illinois.gov/news/rss.xml", name: "IL IDFPR News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.ohio.gov/news/feed/", name: "OH Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.dobs.pa.gov/Documents/News%20Releases/rss.xml", name: "PA Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.gadbf.georgia.gov/news/feed/", name: "GA Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.michigan.gov/difs/news/press-releases/feed/", name: "MI DIFS News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.dbo.nc.gov/news/feed/", name: "NC Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.nj.gov/dobi/news/pressreleases/feed.xml", name: "NJ Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.commerce.state.mn.us/news/rss.xml", name: "MN Commerce News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.az.gov/news/rss/", name: "AZ Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.dora.state.co.us/banking/news/feed/", name: "CO Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.dfi.wi.gov/Pages/Banking/News.aspx?rss=true", name: "WI DFI News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.mo.gov/news/rss/", name: "MO Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.in.gov/news/rss/", name: "IN Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.dobs.state.ga.us/news/feed/", name: "GA Banking News 2", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.tncomptroller.org/banking-news/rss/", name: "TN Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.virginia.gov/news/feed/", name: "VA Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.mass.gov/orgs/division-of-banks/news/feed/", name: "MA Division of Banks News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://dob.ct.gov/news/feed/", name: "CT Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.obre.maryland.gov/news/feed/", name: "MD Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.osbc.state.ks.us/news/rss/", name: "KS Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.sbi.nebraska.gov/news/feed/", name: "NE Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.iowa.gov/news/rss/", name: "IA Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.state.ok.us/news/rss/", name: "OK Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.sc.gov/Banking/news/feed/", name: "SC Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.state.la.us/news/feed/", name: "LA Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.state.al.gov/news/feed/", name: "AL Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.state.ar.us/news/feed/", name: "AR Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.state.ms.us/news/feed/", name: "MS Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.wv.gov/news/feed/", name: "WV Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.ky.gov/news/feed/", name: "KY Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.state.id.us/news/feed/", name: "ID Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://dobs.mt.gov/news/feed/", name: "MT Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://dob.nd.gov/news/feed/", name: "ND Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.sd.gov/news/feed/", name: "SD Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.state.wy.us/news/feed/", name: "WY Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.ut.gov/news/feed/", name: "UT Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.nv.gov/news/feed/", name: "NV Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.nm.gov/news/feed/", name: "NM Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://dob.hi.gov/news/feed/", name: "HI Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.alaska.gov/news/feed/", name: "AK Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.state.me.us/news/feed/", name: "ME Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.state.nh.us/news/feed/", name: "NH Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.state.vt.us/news/feed/", name: "VT Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.ri.gov/news/feed/", name: "RI Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.banking.de.gov/news/feed/", name: "DE Banking News", category: "state", parserType: "rss", pollingFrequencyHours: 24 },
];

const NEWS_SOURCES: MonitorSource[] = [
  { url: "https://news.google.com/rss/search?q=ChexSystems+bank&hl=en-US&gl=US&ceid=US:en", name: "Google News ChexSystems", category: "news", parserType: "rss", pollingFrequencyHours: 3, keywords: ["ChexSystems", "bank account", "denied"] },
  { url: "https://news.google.com/rss/search?q=Early+Warning+Services+bank&hl=en-US&gl=US&ceid=US:en", name: "Google News EWS", category: "news", parserType: "rss", pollingFrequencyHours: 3 },
  { url: "https://news.google.com/rss/search?q=bank+account+bonus+2024&hl=en-US&gl=US&ceid=US:en", name: "Google News Bank Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 3 },
  { url: "https://news.google.com/rss/search?q=bank+checking+account+policy+change&hl=en-US&gl=US&ceid=US:en", name: "Google News Bank Policy", category: "news", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://news.google.com/rss/search?q=second+chance+checking+account&hl=en-US&gl=US&ceid=US:en", name: "Google News Second Chance", category: "news", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://news.google.com/rss/search?q=Zelle+fraud+bank+policy&hl=en-US&gl=US&ceid=US:en", name: "Google News Zelle Policy", category: "news", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://news.google.com/rss/search?q=bank+account+denial+discrimination&hl=en-US&gl=US&ceid=US:en", name: "Google News Bank Denial", category: "news", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://news.google.com/rss/search?q=consumer+financial+protection+bureau+banking&hl=en-US&gl=US&ceid=US:en", name: "Google News CFPB Banking", category: "news", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://news.google.com/rss/search?q=Chase+bank+account+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News Chase Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=Bank+of+America+checking+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News BofA Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=Wells+Fargo+checking+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News WF Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=Citibank+checking+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News Citi Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=US+Bank+checking+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News US Bank Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=TD+Bank+checking+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News TD Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=Ally+Bank+bonus+rate&hl=en-US&gl=US&ceid=US:en", name: "Google News Ally Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=SoFi+bank+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News SoFi Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=Marcus+Goldman+Sachs+savings+rate&hl=en-US&gl=US&ceid=US:en", name: "Google News Marcus Rate", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=Capital+One+360+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News C1 Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=Discover+Bank+bonus+savings&hl=en-US&gl=US&ceid=US:en", name: "Google News Discover Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=PNC+bank+checking+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News PNC Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=Regions+bank+checking+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News Regions Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=Fifth+Third+bank+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News Fifth Third Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=Huntington+bank+checking+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News Huntington Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=KeyBank+checking+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News KeyBank Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=Citizens+Bank+checking+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News Citizens Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=BMO+Harris+checking+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News BMO Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=Truist+checking+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News Truist Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=Comerica+checking+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News Comerica Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=Wintrust+bank+checking+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News Wintrust Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=online+bank+account+bonus+offer&hl=en-US&gl=US&ceid=US:en", name: "Google News Online Bank Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=credit+union+checking+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News CU Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://news.google.com/rss/search?q=direct+deposit+requirement+bank+bonus&hl=en-US&gl=US&ceid=US:en", name: "Google News DD Bonus", category: "news", parserType: "rss", pollingFrequencyHours: 4 },
];

const CONSUMER_SOURCES: MonitorSource[] = [
  { url: "https://www.bbb.org/api/rss?category=banking&type=complaint", name: "BBB Banking Complaints", category: "consumer", parserType: "rss", pollingFrequencyHours: 12, keywords: ["ChexSystems", "EWS", "denied", "closed"] },
  { url: "https://trustpilot.com/review/chexsystems.com?sort=recency", name: "Trustpilot ChexSystems", category: "consumer", parserType: "html", pollingFrequencyHours: 12 },
  { url: "https://www.trustpilot.com/review/earlywarning.com?sort=recency", name: "Trustpilot EWS", category: "consumer", parserType: "html", pollingFrequencyHours: 12 },
  { url: "https://www.yelp.com/biz/chex-systems-eden-prairie", name: "Yelp ChexSystems", category: "consumer", parserType: "html", pollingFrequencyHours: 24 },
  { url: "https://www.consumeraffairs.com/finance/chexsystems.json", name: "ConsumerAffairs ChexSystems", category: "consumer", parserType: "json", pollingFrequencyHours: 12 },
  { url: "https://www.pissedconsumer.com/chex-systems-reviews.html", name: "PissedConsumer ChexSystems", category: "consumer", parserType: "html", pollingFrequencyHours: 24 },
  { url: "https://www.sitejabber.com/reviews/chexsystems.com", name: "SiteJabber ChexSystems", category: "consumer", parserType: "html", pollingFrequencyHours: 24 },
  { url: "https://www.bankrate.com/banking/checking-account/best-second-chance-checking-accounts/", name: "Bankrate Second Chance Accounts", category: "consumer", parserType: "html", pollingFrequencyHours: 24 },
  { url: "https://www.nerdwallet.com/best/banking/second-chance-checking", name: "NerdWallet Second Chance", category: "consumer", parserType: "html", pollingFrequencyHours: 24 },
  { url: "https://www.mybanktracker.com/checking-account/banks-dont-use-chexsystems", name: "MyBankTracker No ChexSystems", category: "consumer", parserType: "html", pollingFrequencyHours: 24 },
  { url: "https://wallethub.com/answers/ba/banks-that-dont-use-chexsystems-2140716820/", name: "WalletHub No ChexSystems", category: "consumer", parserType: "html", pollingFrequencyHours: 24 },
  { url: "https://www.creditkarma.com/checking/i/no-chexsystems-banks", name: "CreditKarma No ChexSystems", category: "consumer", parserType: "html", pollingFrequencyHours: 24 },
  { url: "https://thecollegeinvestor.com/35088/banks-dont-use-chexsystems/", name: "College Investor No ChexSystems", category: "consumer", parserType: "html", pollingFrequencyHours: 24 },
  { url: "https://www.depositaccounts.com/checking/chexsystems.html", name: "Deposit Accounts ChexSystems List", category: "consumer", parserType: "html", pollingFrequencyHours: 12 },
  { url: "https://www.gobankingrates.com/banking/banks-use-chexsystems/", name: "GOBankingRates ChexSystems Banks", category: "consumer", parserType: "html", pollingFrequencyHours: 24 },
  { url: "https://www.lendingtree.com/checking/second-chance-checking-account/", name: "LendingTree Second Chance", category: "consumer", parserType: "html", pollingFrequencyHours: 24 },
  { url: "https://www.fool.com/the-ascent/banks/second-chance-checking/", name: "Motley Fool Second Chance", category: "consumer", parserType: "html", pollingFrequencyHours: 24 },
  { url: "https://smartasset.com/checking-account/banks-that-dont-use-chexsystems", name: "SmartAsset No ChexSystems", category: "consumer", parserType: "html", pollingFrequencyHours: 24 },
  { url: "https://www.consumerreports.org/money/banking/how-to-get-a-bank-account-even-with-bad-banking-history/", name: "CR Bad Banking History", category: "consumer", parserType: "html", pollingFrequencyHours: 48 },
  { url: "https://www.checkingaccountexpert.com/banks-dont-use-chexsystems/", name: "Checking Account Expert", category: "consumer", parserType: "html", pollingFrequencyHours: 24 },
];

const EXTRA_BANK_NEWSROOM_SOURCES: MonitorSource[] = [
  { url: "https://ir.jpmorganchase.com/news-releases/rss/news-releases.xml", name: "JPMorgan Chase IR News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://investor.bankofamerica.com/press-releases/rss", name: "Bank of America Investor News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://newsroom.bankofamerica.com/content/newsroom/home.rss.xml", name: "Bank of America Newsroom", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://newsroom.wf.com/rss/feeds/newsroom-rss.xml", name: "Wells Fargo Newsroom", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.citigroup.com/citi/news/rss.xml", name: "Citigroup News RSS", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://ir.usbank.com/news-releases/rss/news-releases.xml", name: "US Bancorp IR News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://newsroom.pnc.com/rss/pnc-news.xml", name: "PNC Newsroom RSS", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.truist.com/news-releases/rss/news-releases.xml", name: "Truist IR News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.td.com/news-releases/rss/news-releases.xml", name: "TD Bank IR News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.capitalone.com/news-releases/rss/news-releases.xml", name: "Capital One IR News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://ir.regions.com/news-releases/rss/news-releases.xml", name: "Regions Financial IR News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.huntington.com/news-releases/rss/news-releases.xml", name: "Huntington Bancshares IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.citizensfinancialgroup.com/news-releases/rss/news-releases.xml", name: "Citizens Financial IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.mtb.com/news-releases/rss/news-releases.xml", name: "M&T Bank IR News", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.ally.com/news-releases/rss/news-releases.xml", name: "Ally Financial IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://ir.sofi.com/news-releases/rss/news-releases.xml", name: "SoFi Technologies IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://ir.firsthorizon.com/news-releases/rss/news-releases.xml", name: "First Horizon IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.westernalliance.com/news-releases/rss/news-releases.xml", name: "Western Alliance IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.cadencebank.com/news-releases/rss/news-releases.xml", name: "Cadence Bank IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.pinnaclefi.com/news-releases/rss/news-releases.xml", name: "Pinnacle Financial IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.bankunited.com/news-releases/rss/news-releases.xml", name: "BankUnited IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.homestreet.com/news-releases/rss/news-releases.xml", name: "HomeStreet IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.renasant.com/news-releases/rss/news-releases.xml", name: "Renasant Corp IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.columbiabanksystem.com/news-releases/rss/news-releases.xml", name: "Columbia Banking IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.pacificpremier.com/news-releases/rss/news-releases.xml", name: "Pacific Premier Bancorp IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.glacierbancorp.com/news-releases/rss/news-releases.xml", name: "Glacier Bancorp IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.bannerbank.com/news-releases/rss/news-releases.xml", name: "Banner Financial IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.enterprisebancorp.com/news-releases/rss/news-releases.xml", name: "Enterprise Bancorp IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.fnb-corp.com/news-releases/rss/news-releases.xml", name: "FNB Corp IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.heartlandfinancial.com/news-releases/rss/news-releases.xml", name: "Heartland Financial IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.wintrust.com/news-releases/rss/news-releases.xml", name: "Wintrust Financial IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.texascapitalbank.com/news-releases/rss/news-releases.xml", name: "Texas Capital Bank IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.prosperitybankshares.com/news-releases/rss/news-releases.xml", name: "Prosperity Bancshares IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.veritexbank.com/news-releases/rss/news-releases.xml", name: "Veritex Community Bank IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.cullenfrob.com/news-releases/rss/news-releases.xml", name: "Cullen/Frost Bankers IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.atlanticunionbankshares.com/news-releases/rss/news-releases.xml", name: "Atlantic Union Bankshares IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.southstatebank.com/news-releases/rss/news-releases.xml", name: "South State Bank IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://investor.firsthawaiian.com/news-releases/rss/news-releases.xml", name: "First Hawaiian Bank IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 48 },
  { url: "https://ir.boh.com/news-releases/rss/news-releases.xml", name: "Bank of Hawaii IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 48 },
  { url: "https://ir.centralpacificfinancial.com/news-releases/rss/news-releases.xml", name: "Central Pacific Financial IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 48 },
  { url: "https://ir.synchronyfinancial.com/news-releases/rss/news-releases.xml", name: "Synchrony Financial IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://ir.americanexpress.com/news-releases/rss/news-releases.xml", name: "American Express IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://ir.goldmansachs.com/news-releases/rss/news-releases.xml", name: "Goldman Sachs IR (Marcus)", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://ir.morganstanley.com/news-releases/rss/news-releases.xml", name: "Morgan Stanley IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://ir.bmo.com/news-releases/rss/news-releases.xml", name: "BMO Financial IR", category: "bank_newsroom", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.usaa.com/inet/wc/news-releases-index", name: "USAA News", category: "bank_newsroom", parserType: "html", pollingFrequencyHours: 48 },
  { url: "https://navyfederal.org/about/news/press-releases/", name: "Navy Federal Press Releases", category: "bank_newsroom", parserType: "html", pollingFrequencyHours: 48 },
  { url: "https://www.penfed.org/about-penfed/newsroom", name: "PenFed Newsroom", category: "bank_newsroom", parserType: "html", pollingFrequencyHours: 48 },
  { url: "https://www.becu.org/about/news", name: "BECU News", category: "bank_newsroom", parserType: "html", pollingFrequencyHours: 48 },
  { url: "https://www.alliantcreditunion.org/about-alliant/press-room", name: "Alliant Credit Union Press", category: "bank_newsroom", parserType: "html", pollingFrequencyHours: 48 },
  { url: "https://seacoastbanking.com/about/investor-relations/press-releases/", name: "Seacoast Banking Press Releases", category: "bank_newsroom", parserType: "html", pollingFrequencyHours: 48 },
  { url: "https://www.firstnational.com/about-us/news-releases", name: "First National Bank News", category: "bank_newsroom", parserType: "html", pollingFrequencyHours: 48 },
  { url: "https://chime.com/press/", name: "Chime Press Room", category: "bank_newsroom", parserType: "html", pollingFrequencyHours: 24 },
  { url: "https://current.com/blog/", name: "Current Blog", category: "bank_newsroom", parserType: "html", pollingFrequencyHours: 24 },
  { url: "https://www.varo.com/press", name: "Varo Bank Press", category: "bank_newsroom", parserType: "html", pollingFrequencyHours: 48 },
];

const MAJOR_BANKS = [
  "chase", "bank-of-america", "wells-fargo", "citibank", "us-bank", "pnc-bank",
  "truist", "td-bank", "capital-one", "fifth-third", "regions-bank", "huntington",
  "citizens-bank", "keybank", "mt-bank", "comerica", "ally-bank", "sofi-bank",
  "discover-bank", "american-express", "charles-schwab-bank", "fidelity-bank",
  "vanguard-bank", "bmo-harris", "hsbc-usa", "barclays-us", "synchrony-bank",
  "marcus-by-gs", "navy-federal-credit-union", "usaa", "boeing-employees-credit-union",
  "pentagon-federal-credit-union", "state-employees-credit-union", "becu",
  "first-national-bank", "first-midwest-bank", "wintrust-financial", "pinnacle-bank",
  "west-bank", "glacier-bank", "banner-bank", "columbia-bank", "centerstate-bank",
  "south-state-bank", "atlantic-capital-bank", "international-bank-of-commerce",
  "veritex-community-bank", "texas-capital-bank", "prosperity-bank", "independent-bank",
  "western-alliance-bank", "bankunited", "seacoast-banking", "lakeland-bancorp",
  "homestreet-bank", "renasant-corp", "first-horizon", "cadence-bank", "pinnacle-fp",
  "atlantic-union-bank", "enterprise-bancorp", "columbia-banking", "pacific-premier",
  "central-pacific-financial", "first-hawaiian-bank", "bank-of-hawaii", "american-savings",
  "first-tech-federal-cu", "digital-federal-cu", "alliant-credit-union", "penfed",
  "bethpage-federal-cu", "schools-first-fcu", "golden-1-cu", "delta-community-cu",
  "suncoast-credit-union", "landmark-credit-union", "lake-michigan-cu", "ent-credit-union",
  "redstone-federal-cu", "wright-patt-cu", "security-service-fcu", "truliant-fcu",
  "connexus-credit-union", "onpoint-community-cu", "oregonians-cu", "unify-financial-cu",
  "kinecta-federal-cu", "california-coast-cu", "premier-america-cu", "logix-federal-cu",
  "meriwest-cu", "mission-federal-cu", "san-diego-county-cu", "provident-cu",
  "patelco-cu", "travis-cu", "safe-cu", "star-one-cu", "stanford-fcu",
  "nasa-fcu", "space-coast-cu", "fairwinds-cu", "lockheed-fcu", "air-force-fcu",
  "armed-forces-bank", "community-america-cu", "horizon-cu", "first-western-financial",
  "enterprise-bank-and-trust", "veritex-bank", "texas-capital", "prosperity-bancshares",
];

function generateCFPBBankComplaints(): MonitorSource[] {
  return MAJOR_BANKS.map((bank): MonitorSource => ({
    url: `https://www.consumerfinance.gov/data-research/consumer-complaints/search/api/v1/?format=json&company=${encodeURIComponent(bank.replace(/-/g, " "))}&size=25`,
    name: `CFPB Complaints — ${bank.replace(/-/g, " ").replace(/\b\w/g, c => c.toUpperCase())}`,
    category: "cfpb",
    parserType: "json",
    pollingFrequencyHours: 12,
    keywords: ["ChexSystems", "EWS", "denied", "account"],
  }));
}

function generateGoogleNewsBankSearches(): MonitorSource[] {
  const searches = [
    "bank+account+policy+change+ChexSystems",
    "early+warning+services+bank+denial",
    "second+chance+checking+account+open",
    "bank+bonus+checking+soft+pull",
    "bank+account+denied+consumer+report",
    "chexsystems+dispute+bank+account",
    "bank+bonus+direct+deposit+requirement",
    "bank+account+minimum+balance+waived",
    "bank+opened+chexsystems+free+2024",
    "bank+no+minimum+balance+bonus",
    "bank+account+closed+early+warning",
    "Zelle+fraud+bank+policy+update",
    "bank+checking+account+fee+waived",
    "bank+bonus+nationwide+offer",
    "credit+union+checking+bonus+no+fee",
    "bank+account+hard+pull+policy",
    "bank+account+soft+pull+nationwide",
    "bank+account+direct+deposit+alternative",
    "bank+account+bonus+new+2025",
    "bank+opened+second+chance+program",
    "bank+closed+account+EWS+report",
    "bank+account+bonus+expired+2025",
    "bank+policy+update+consumer+reporting",
    "bank+account+approval+chexsystems+free",
    "online+bank+account+no+credit+check",
    "neobank+checking+account+bonus",
    "fintech+bank+account+bonus",
    "CFPB+bank+account+rule",
    "bank+account+portability+rule",
    "open+banking+regulation+consumer",
    "debit+card+rewards+bank+bonus",
    "bank+account+sign+up+bonus+2025",
    "checking+account+promo+offer+2025",
    "savings+account+bonus+high+yield",
    "money+market+account+bonus",
    "certificate+deposit+bonus",
    "bank+referral+bonus+program",
    "bank+account+opening+minimum+deposit",
    "bank+relationship+bonus",
    "business+checking+account+bonus",
  ];
  return searches.map((q): MonitorSource => ({
    url: `https://news.google.com/rss/search?q=${q}&hl=en-US&gl=US&ceid=US:en`,
    name: `Google News — ${q.replace(/\+/g, " ").slice(0, 50)}`,
    category: "news",
    parserType: "rss",
    pollingFrequencyHours: 6,
    keywords: ["ChexSystems", "EWS", "bank bonus", "policy"],
  }));
}

function generateDocTagSearches(): MonitorSource[] {
  const banks = [
    "huntington", "pnc", "regions", "fifth-third", "td-bank", "keycorp",
    "citizens-bank", "m-t-bank", "truist", "ally-bank", "sofi", "chime",
    "synchrony", "capital-one", "discover", "navy-federal", "usaa", "becu",
    "first-national-bank", "wintrust", "pinnacle", "cadence-bank",
    "independent-bank", "western-alliance", "glacier-bank", "banner-bank",
    "columbia-bank", "south-state-bank", "centerstate-bank", "veritex",
    "texas-capital", "prosperity-bank", "international-bank-commerce",
    "atlantic-union", "enterprise-bancorp", "first-midwest-bank",
    "first-horizon", "atlantic-capital", "lakeland-bancorp", "homestreet",
    "seacoast-banking", "first-hawaiian", "bank-of-hawaii", "american-savings",
    "patelco", "golden-1", "delta-community", "suncoast", "landmark",
    "lake-michigan-credit-union", "ent-credit-union", "redstone",
    "connexus", "onpoint", "unify-financial", "kinecta", "logix",
    "penfed", "pentagon-federal", "state-employees-credit-union",
    "schools-first", "bethpage", "alliant", "digital-federal",
    "first-tech-federal", "nasa-fcu", "space-coast", "fairwinds",
    "armed-forces-bank", "community-america",
  ];
  return banks.map((bank): MonitorSource => ({
    url: `https://www.doctorofcredit.com/tag/${bank}/feed/`,
    name: `DoC — ${bank.replace(/-/g, " ").replace(/\b\w/g, c => c.toUpperCase())}`,
    category: "doc",
    parserType: "rss",
    pollingFrequencyHours: 6,
  }));
}

function generateCFPBProductComplaints(): MonitorSource[] {
  const products = [
    "Checking or savings account",
    "Bank account or service",
    "Credit reporting",
    "Debt collection",
    "Money transfers",
    "Payday loan",
    "Prepaid card",
    "Other financial service",
    "Virtual currency",
  ];
  const issues = [
    "Opening an account",
    "Closing an account",
    "Deposits and withdrawals",
    "Managing an account",
    "Using a debit or ATM card",
    "Problem caused by your funds being low",
    "Fraud or scam",
    "Unexpected or other fees",
  ];
  const result: MonitorSource[] = [];
  for (const product of products) {
    for (const issue of issues.slice(0, 6)) {
      result.push({
        url: `https://www.consumerfinance.gov/data-research/consumer-complaints/search/api/v1/?format=json&product=${encodeURIComponent(product)}&issue=${encodeURIComponent(issue)}&size=10`,
        name: `CFPB — ${product.slice(0, 25)} / ${issue.slice(0, 20)}`,
        category: "cfpb",
        parserType: "json",
        pollingFrequencyHours: 24,
        keywords: ["ChexSystems", "EWS", "denial"],
      });
    }
  }
  return result;
}

function generateRedditBankSearches(): MonitorSource[] {
  const subreddits = [
    "churning", "personalfinance", "banking", "CreditCards", "frugal",
    "financialindependence", "investing", "povertyfinance", "beermoney", "deals",
  ];
  const queries = [
    "chexsystems+bank+account", "early+warning+services+bank",
    "bank+bonus+data+point", "bank+account+denied+report",
    "no+chexsystems+bank+opened", "second+chance+bank+account",
    "bank+policy+change", "bank+account+approval+denied",
  ];
  const result: MonitorSource[] = [];
  for (const sub of subreddits) {
    for (const q of queries.slice(0, 5)) {
      result.push({
        url: `https://www.reddit.com/r/${sub}/search.json?q=${q}&sort=new&limit=25&t=week`,
        name: `Reddit r/${sub} — ${q.replace(/\+/g, " ").slice(0, 30)}`,
        category: "reddit",
        parserType: "json",
        pollingFrequencyHours: 8,
        keywords: ["ChexSystems", "EWS", "denied", "bonus"],
      });
    }
  }
  return result;
}

const EXTRA_AGGREGATOR_SOURCES: MonitorSource[] = [
  { url: "https://www.consumeraffairs.com/finance/banks.json", name: "ConsumerAffairs Banks JSON", category: "consumer", parserType: "json", pollingFrequencyHours: 12 },
  { url: "https://www.kiplinger.com/personal-finance/banking/rss", name: "Kiplinger Banking RSS", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.moneycrashers.com/category/banking/feed/", name: "Money Crashers Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.thebalancemoney.com/banking-4427799/rss.xml", name: "The Balance Money Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://doughroller.net/feed/", name: "DoughRoller Feed", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://money.com/money/feed/", name: "Money Magazine Feed", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.huffpost.com/section/money/feed", name: "HuffPost Money Feed", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://fortune.com/section/finance/feed/", name: "Fortune Finance Feed", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.businessinsider.com/finance/rss", name: "Business Insider Finance", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://www.marketwatch.com/rss/realtimeheadlines", name: "MarketWatch Headlines", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=BAC&region=US&lang=en-US", name: "Yahoo Finance BofA", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=JPM&region=US&lang=en-US", name: "Yahoo Finance Chase", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=WFC&region=US&lang=en-US", name: "Yahoo Finance WF", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=C&region=US&lang=en-US", name: "Yahoo Finance Citi", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=USB&region=US&lang=en-US", name: "Yahoo Finance US Bank", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=PNC&region=US&lang=en-US", name: "Yahoo Finance PNC", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=TFC&region=US&lang=en-US", name: "Yahoo Finance Truist", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=COF&region=US&lang=en-US", name: "Yahoo Finance C1", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=ALLY&region=US&lang=en-US", name: "Yahoo Finance Ally", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=SOFI&region=US&lang=en-US", name: "Yahoo Finance SoFi", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=DFS&region=US&lang=en-US", name: "Yahoo Finance Discover", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=SCHW&region=US&lang=en-US", name: "Yahoo Finance Schwab", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=FITB&region=US&lang=en-US", name: "Yahoo Finance 5th 3rd", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=RF&region=US&lang=en-US", name: "Yahoo Finance Regions", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=HBAN&region=US&lang=en-US", name: "Yahoo Finance Huntington", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=CFG&region=US&lang=en-US", name: "Yahoo Finance Citizens", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=KEY&region=US&lang=en-US", name: "Yahoo Finance KeyCorp", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=MTB&region=US&lang=en-US", name: "Yahoo Finance M&T", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=CMA&region=US&lang=en-US", name: "Yahoo Finance Comerica", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://finance.yahoo.com/rss/2.0/headline?s=TD&region=US&lang=en-US", name: "Yahoo Finance TD", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://seekingalpha.com/tag/banking/feed.xml", name: "SeekingAlpha Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://seekingalpha.com/tag/chexsystems/feed.xml", name: "SeekingAlpha ChexSystems", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.zerohedge.com/feed/banking", name: "ZeroHedge Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.thestreet.com/topic/46377/banking.rss", name: "TheStreet Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.creditcards.com/news/feed.xml", name: "CreditCards.com News", category: "aggregator", parserType: "rss", pollingFrequencyHours: 8 },
  { url: "https://www.magnifymoney.com/feed/", name: "MagnifyMoney Feed", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.nerdwallet.com/blog/feed/", name: "NerdWallet Blog", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.bankrate.com/feed/", name: "Bankrate Full Feed", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.investopedia.com/rss.xml", name: "Investopedia RSS", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://www.thebalancemoney.com/rss.xml", name: "The Balance Full RSS", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://money.usnews.com/rss", name: "US News Money RSS", category: "aggregator", parserType: "rss", pollingFrequencyHours: 8 },
  { url: "https://news.ycombinator.com/rss?tag=banking", name: "HN Banking", category: "forum", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://dev.to/feed/tag/banking", name: "Dev.to Banking", category: "forum", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://medium.com/tag/banking/feed", name: "Medium Banking Tag", category: "forum", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://medium.com/tag/fintech/feed", name: "Medium Fintech Tag", category: "forum", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://medium.com/tag/bank-bonus/feed", name: "Medium Bank Bonus", category: "forum", parserType: "rss", pollingFrequencyHours: 8 },
  { url: "https://medium.com/tag/chexsystems/feed", name: "Medium ChexSystems", category: "forum", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://www.linkedin.com/rss/tag?tag=banking", name: "LinkedIn Banking", category: "aggregator", parserType: "rss", pollingFrequencyHours: 12 },
  { url: "https://bankingdive.com/rss/news", name: "Banking Dive RSS", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://www.paymentsdive.com/feeds/news/", name: "Payments Dive News", category: "aggregator", parserType: "rss", pollingFrequencyHours: 4 },
  { url: "https://www.creditunionjournal.com/feeds/news/", name: "CU Journal News", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://cutoday.info/feed/", name: "CU Today Feed", category: "aggregator", parserType: "rss", pollingFrequencyHours: 6 },
  { url: "https://ncua.gov/regulation-supervision/news-blog/feed", name: "NCUA Blog Feed", category: "federal", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.fdic.gov/news/financial-institution-letters/feed.xml", name: "FDIC FIL Feed", category: "federal", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://www.occ.gov/news-issuances/interpretations-and-actions/feed.xml", name: "OCC Interpretations", category: "federal", parserType: "rss", pollingFrequencyHours: 24 },
  { url: "https://efts.sec.gov/LATEST/search-index?q=%22ChexSystems%22&dateRange=custom&startdt=2023-01-01&forms=8-K", name: "SEC Filings ChexSystems", category: "federal", parserType: "json", pollingFrequencyHours: 24 },
  { url: "https://efts.sec.gov/LATEST/search-index?q=%22Early+Warning+Services%22&forms=8-K&dateRange=custom&startdt=2023-01-01", name: "SEC Filings EWS", category: "federal", parserType: "json", pollingFrequencyHours: 24 },
  { url: "https://efts.sec.gov/LATEST/search-index?q=%22bank+account+bonus%22&forms=S-1&dateRange=custom&startdt=2023-01-01", name: "SEC Filings Bank Bonus", category: "federal", parserType: "json", pollingFrequencyHours: 48 },
];

export const ALL_SOURCES: MonitorSource[] = [
  ...CFPB_SOURCES,
  ...REDDIT_SOURCES,
  ...DOC_SOURCES,
  ...BANK_NEWSROOM_SOURCES,
  ...AGGREGATOR_SOURCES,
  ...FORUM_SOURCES,
  ...FEDERAL_SOURCES,
  ...STATE_SOURCES,
  ...NEWS_SOURCES,
  ...CONSUMER_SOURCES,
  ...EXTRA_BANK_NEWSROOM_SOURCES,
  ...generateCFPBBankComplaints(),
  ...generateGoogleNewsBankSearches(),
  ...generateDocTagSearches(),
  ...generateCFPBProductComplaints(),
  ...generateRedditBankSearches(),
  ...EXTRA_AGGREGATOR_SOURCES,
];

export function getSourcesByCategory(category: MonitorSource["category"]): MonitorSource[] {
  return ALL_SOURCES.filter(s => s.category === category);
}

export function getSourcesDueForCheck(lastCheckedMs: number, nowMs: number = Date.now()): MonitorSource[] {
  return ALL_SOURCES.filter(s => {
    const interval = s.pollingFrequencyHours * 3600 * 1000;
    return nowMs - lastCheckedMs >= interval;
  });
}

export const SOURCE_COUNT = ALL_SOURCES.length;
